#if !canImport(ObjectiveC)
import XCTest

extension FutureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureTests = [
        ("testFutureIsCold", testFutureIsCold),
        ("testResolveAsynchronously", testResolveAsynchronously),
        ("testResolveSynchronously", testResolveSynchronously),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FutureTests.__allTests__FutureTests),
    ]
}
#endif
